#!/bin/sh

terraform state mv aws_cloudwatch_log_group.gateway_logs aws_cloudwatch_log_group.websockets_gateway_logs
terraform state mv aws_acm_certificate.pointing_cert aws_acm_certificate.websockets_pointing_cert
terraform state mv aws_apigatewayv2_api.pointing aws_apigatewayv2_api.websockets_pointing
terraform state mv aws_apigatewayv2_deployment.pointing aws_apigatewayv2_deployment.websockets_pointing
terraform state mv aws_apigatewayv2_stage.pointing_stage aws_apigatewayv2_stage.websockets_pointing_stage
terraform state mv aws_apigatewayv2_api_mapping.pointing aws_apigatewayv2_api_mapping.websockets_pointing
terraform state mv aws_apigatewayv2_domain_name.pointing aws_apigatewayv2_domain_name.websockets_pointing
terraform state mv aws_route53_record.pointing aws_route53_record.websockets_pointing