name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.12
        id: go

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: cd frontend && npm install

      - name: Generate .env.local file
        run: echo 'VUE_APP_POINTING_SOCKET_URL=wss://pointing.pointypoints.com' > frontend/.env.local

      - name: Test Front End
        run: make frontend-test

      # will be talking to local dynamo but need something that looks like creds on the env
      - name: Test Back End
        run: AWS_ACCESS_KEY_ID=GARBAGE AWS_SECRET_ACCESS_KEY=MOREGARBAGE AWS_DEFAULT_REGION=us-east-1 make backend-test

      # for good measure make sure everything builds
      - name: Build
        run: make build